[build]
  # No build command needed for static site
  publish = "."

[[headers]]
  # Apply these headers to all routes
  for = "/*"
  [headers.values]
    # Enable CORS for data files
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  # Specific headers for JSON data files
  for = "/data/*"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=3600"
